trainer:
  dataset: T45
  is_train: True
  warmup: 2
  num_epochs: 100
  lr: [0.1, 0.1, 0.1]
  sf: [0.1, 0.1, 0.1]
  g: [0.94, 0.95, 0.99]
  # ms: [20,39,60]   # RIT
  ms: [9,18,58]    # Rendezvous
  power: 0.1
  top: 5
  optimizer: adamw
  decay_rate: 0.99
  weight_decay: 0.05
  weight_decay_end: 0.04
  val_training: False
  resume: 
    train: True
    test: False
  

finetune:
  checkpoint: Rendezvous
  # checkpoint: RIT

dataset:
  T45:
    batch_size: 4
    class_num: 100
    num_workers: 4
    kfold: 1
    data_dir: '/root/.cache/huggingface/forget/datasets/CholecT45/'
    text_path: '/workspace/Jeming/Triple_git/src/text-data/'  # change to adapt your path
    dataset_variant: 'cholect45-crossval'
    pin_memory: True
    persistent_workers: True
    drop_last: False
    weight_randa: True
    data_augmentations: ['original', 'vflip', 'hflip', 'contrast', 'rot90']
  T50:
    batch_size: 32
    class_num: 100
    num_workers: 4
    kfold: 1
    data_dir: '/root/.cache/huggingface/forget/datasets/CholecT50/'
    text_path: '/workspace/Jeming/Triple_git/src/text-data/'   # change to adapt your path
    m: 3
    weight_randa: False
    data_augmentations: ['rot90', 'hflip', 'contrast', 'original']
    dataset_variant: 'cholect45-crossval'
  
    