trainer:
  is_train: True
  num_epochs: 100
  # lr: [0.01, 0.01, 0.01]
  lr: [0.1, 0.1, 0.1]
  sf: [0.1, 0.1, 0.1]
  g: [0.94, 0.95, 0.99]
  # ms: [20,39,60]   # RIT
  ms: [9,18,58]    # Rendezvous
  power: 0.1
  top: 5
  optimizer: sgd
  decay_rate: 0.99
  weight_decay: 0.05
  weight_decay_end: 0.04
  val_training: False
  resume: 
    train: True
    test: False
  

finetune:
  checkpoint: Rendezvous
  # checkpoint: RIT

dataset:
  batch_size: 32
  class_num: 100
  num_workers: 4
  kfold: 1
  data_dir: '/root/.cache/huggingface/forget/datasets/CholecT45/'
  dataset_variant: 'cholect45-crossval'
  pin_memory: True
  persistent_workers: True
  drop_last: False
  weight_randa: True
  data_augmentations: ['original', 'vflip', 'hflip', 'contrast', 'rot90']